# This make file contains the current set of common sources,
# i.e., sources that are not specific for a platform

NONARCHSRCS=\
	account.c \
	addressbook.c \
	addresslist.c \
	arrays.c \
	atcleanup.c \
	boyermoore.c \
	codecs.c \
	codesets.c \
	configuration.c \
	coroutines_sockets.c \
	coroutines.c \
	dbx.c \
	debug.c \
	estimate.c \
	filter.c \
	folder.c \
	folder_search_thread.c \
	hash.c \
	hmac_md5.c \
	http.c \
	imap.c \
	imap_helper.c \
	imap_thread.c \
	index.c \
	index_external.c \
	index_naive.c \
	lists.c \
	logging.c \
	mail.c \
	mail_context.c \
	mail_support.c \
	mailinfo_extractor.c \
	mbox.c \
	md5.c \
	parse.c \
	pgp.c \
	phrase.c \
	pop3.c \
	pop3_uidl.c \
	print.c \
	progmon.c \
	punycode.c \
	ringbuffer.c \
	signature.c \
	simplemail.c \
	smintl.c \
	smtp.c \
	spam.c \
	ssl.c \
	status.c \
	string_lists.c \
	string_pools.c \
	support_indep.c \
	taglines.c \
	tcp.c \
	text2html.c \
	trans.c
